TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += dg645.db
DB += dg645_logic.db
DB += dg645_delay.db
DB += dg645_width.db
DATA += dg645.proto

#=======================================
include $(TOP)/configure/RULES
