TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += dg645.db
DB += dg645_logic.db
DB += dg645_delay.db
DB += dg645_width.db
DB += dg645_delay_width_shared.db
DB += litron.db

#=======================================
include $(TOP)/configure/RULES
